import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "@/utils/api";
import { useEffect } from "react";

const Home: NextPage = () => {
  const page = api.wiki.getPage.useQuery({ title: "joy division" });

  useEffect(() => {
    console.log(page.data?.page);
  }, [page]);

  return (
    <>
      <Head>
        <title>WikiInterviews</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center"></main>
    </>
  );
};

export default Home;
